# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\advanced.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.setEnabled(True)
        # Dialog.resize(304, 623)
        Dialog.setToolTip("")
        Dialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_login = QtWidgets.QLabel(Dialog)
        self.label_login.setObjectName("label_login")
        self.verticalLayout.addWidget(self.label_login)
        self.frame_login = QtWidgets.QFrame(Dialog)
        self.frame_login.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login.setObjectName("frame_login")
        self.formLayout = QtWidgets.QFormLayout(self.frame_login)
        self.formLayout.setObjectName("formLayout")
        self.login_label_id = QtWidgets.QLabel(self.frame_login)
        self.login_label_id.setObjectName("login_label_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.login_label_id)
        self.login_lineEdit_id = QtWidgets.QLineEdit(self.frame_login)
        self.login_lineEdit_id.setObjectName("login_lineEdit_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.login_lineEdit_id)
        self.login_label_key = QtWidgets.QLabel(self.frame_login)
        self.login_label_key.setObjectName("login_label_key")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.login_label_key)
        self.login_lineEdit_key = QtWidgets.QLineEdit(self.frame_login)
        self.login_lineEdit_key.setObjectName("login_lineEdit_key")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.login_lineEdit_key)
        self.login_label_secret = QtWidgets.QLabel(self.frame_login)
        self.login_label_secret.setObjectName("login_label_secret")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.login_label_secret)
        self.login_lineEdit_secret = QtWidgets.QLineEdit(self.frame_login)
        self.login_lineEdit_secret.setEchoMode(QtWidgets.QLineEdit.Password)
        self.login_lineEdit_secret.setObjectName("login_lineEdit_secret")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.login_lineEdit_secret)
        self.verticalLayout.addWidget(self.frame_login)
        self.label_reg = QtWidgets.QLabel(Dialog)
        self.label_reg.setObjectName("label_reg")
        self.verticalLayout.addWidget(self.label_reg)
        self.frame_reg = QtWidgets.QFrame(Dialog)
        self.frame_reg.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_reg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_reg.setObjectName("frame_reg")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_reg)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.reg_label_lay = QtWidgets.QLabel(self.frame_reg)
        self.reg_label_lay.setObjectName("reg_label_lay")
        self.gridLayout_3.addWidget(self.reg_label_lay, 0, 0, 1, 1)
        self.reg_timeEdit = QtWidgets.QTimeEdit(self.frame_reg)
        self.reg_timeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.SecondSection)
        self.reg_timeEdit.setTime(QtCore.QTime(0, 0, 2))
        self.reg_timeEdit.setObjectName("reg_timeEdit")
        self.gridLayout_3.addWidget(self.reg_timeEdit, 0, 1, 1, 2)
        self.reg_label_num = QtWidgets.QLabel(self.frame_reg)
        self.reg_label_num.setObjectName("reg_label_num")
        self.gridLayout_3.addWidget(self.reg_label_num, 1, 0, 1, 1)
        self.reg_comboBox = QtWidgets.QComboBox(self.frame_reg)
        self.reg_comboBox.setEditable(True)
        self.reg_comboBox.setObjectName("reg_comboBox")
        self.reg_comboBox.addItem("")
        self.reg_comboBox.addItem("")
        self.reg_comboBox.addItem("")
        self.reg_comboBox.addItem("")
        self.reg_comboBox.addItem("")
        self.reg_comboBox.addItem("")
        self.reg_comboBox.addItem("")
        self.gridLayout_3.addWidget(self.reg_comboBox, 1, 1, 1, 1)
        self.reg_pushButton = QtWidgets.QPushButton(self.frame_reg)
        self.reg_pushButton.setObjectName("reg_pushButton")
        self.gridLayout_3.addWidget(self.reg_pushButton, 1, 2, 1, 1)
        self.reg_label_debug = QtWidgets.QLabel(self.frame_reg)
        self.reg_label_debug.setObjectName("reg_label_debug")
        self.gridLayout_3.addWidget(self.reg_label_debug, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_reg)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_reg)
        self.label_out = QtWidgets.QLabel(Dialog)
        self.label_out.setObjectName("label_out")
        self.verticalLayout.addWidget(self.label_out)
        self.frame_out = QtWidgets.QFrame(Dialog)
        self.frame_out.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_out.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_out.setObjectName("frame_out")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_out)
        self.gridLayout.setObjectName("gridLayout")
        self.out_label_fmt = QtWidgets.QLabel(self.frame_out)
        self.out_label_fmt.setObjectName("out_label_fmt")
        self.gridLayout.addWidget(self.out_label_fmt, 0, 0, 1, 1)
        self.out_label_dir = QtWidgets.QLabel(self.frame_out)
        self.out_label_dir.setObjectName("out_label_dir")
        self.gridLayout.addWidget(self.out_label_dir, 1, 0, 1, 1)
        self.out_lineEdit_dir = QtWidgets.QLineEdit(self.frame_out)
        self.out_lineEdit_dir.setObjectName("out_lineEdit_dir")
        self.gridLayout.addWidget(self.out_lineEdit_dir, 1, 1, 1, 1)
        self.out_lineEdit_title = QtWidgets.QLineEdit(self.frame_out)
        self.out_lineEdit_title.setEnabled(True)
        self.out_lineEdit_title.setObjectName("out_lineEdit_title")
        self.gridLayout.addWidget(self.out_lineEdit_title, 2, 1, 1, 1)
        self.out_comboBox = QtWidgets.QComboBox(self.frame_out)
        self.out_comboBox.setObjectName("out_comboBox")
        self.out_comboBox.addItem("")
        self.out_comboBox.addItem("")
        self.gridLayout.addWidget(self.out_comboBox, 0, 1, 1, 1)
        self.out_label_title = QtWidgets.QLabel(self.frame_out)
        self.out_label_title.setToolTip("")
        self.out_label_title.setWhatsThis("")
        self.out_label_title.setObjectName("out_label_title")
        self.gridLayout.addWidget(self.out_label_title, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_out)
        self.label_advanced = QtWidgets.QLabel(Dialog)
        self.label_advanced.setObjectName("label_advanced")
        self.verticalLayout.addWidget(self.label_advanced)
        self.frame_advanced = QtWidgets.QFrame(Dialog)
        self.frame_advanced.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_advanced.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_advanced.setObjectName("frame_advanced")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_advanced)
        self.gridLayout_2.setContentsMargins(10, 10, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.adv_pushButton_help = QtWidgets.QPushButton(self.frame_advanced)
        self.adv_pushButton_help.setObjectName("adv_pushButton_help")
        self.gridLayout_2.addWidget(self.adv_pushButton_help, 2, 3, 1, 1)
        self.adv_listWidget = QtWidgets.QListWidget(self.frame_advanced)
        self.adv_listWidget.setEnabled(True)
        self.adv_listWidget.setObjectName("adv_listWidget")
        self.gridLayout_2.addWidget(self.adv_listWidget, 4, 0, 1, 4)
        self.adv_checkBox = QtWidgets.QCheckBox(self.frame_advanced)
        self.adv_checkBox.setText("")
        self.adv_checkBox.setObjectName("adv_checkBox")
        self.gridLayout_2.addWidget(self.adv_checkBox, 2, 1, 1, 1)
        self.adv_label_clean = QtWidgets.QLabel(self.frame_advanced)
        self.adv_label_clean.setObjectName("adv_label_clean")
        self.gridLayout_2.addWidget(self.adv_label_clean, 2, 0, 1, 1)
        self.adv_pushButton_add = QtWidgets.QPushButton(self.frame_advanced)
        self.adv_pushButton_add.setObjectName("adv_pushButton_add")
        self.gridLayout_2.addWidget(self.adv_pushButton_add, 2, 2, 1, 1)
        self.adv_label_region = QtWidgets.QLabel(self.frame_advanced)
        self.adv_label_region.setObjectName("adv_label_region")
        self.gridLayout_2.addWidget(self.adv_label_region, 0, 0, 1, 1)
        self.adv_lineEdit = QtWidgets.QLineEdit(self.frame_advanced)
        self.adv_lineEdit.setObjectName("adv_lineEdit")
        self.gridLayout_2.addWidget(self.adv_lineEdit, 0, 2, 1, 2)
        self.verticalLayout.addWidget(self.frame_advanced)
        self.frame_set = QtWidgets.QFrame(Dialog)
        self.frame_set.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_set.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_set.setObjectName("frame_set")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_set)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.set_pushButton_reset = QtWidgets.QPushButton(self.frame_set)
        self.set_pushButton_reset.setObjectName("set_pushButton_reset")
        self.horizontalLayout.addWidget(self.set_pushButton_reset)
        self.set_pushButton_apply = QtWidgets.QPushButton(self.frame_set)
        self.set_pushButton_apply.setObjectName("set_pushButton_apply")
        self.horizontalLayout.addWidget(self.set_pushButton_apply)
        self.verticalLayout.addWidget(self.frame_set)

        self.retranslateUi(Dialog)
        self.set_pushButton_reset.clicked.connect(Dialog.set_resetSlot)
        self.set_pushButton_apply.clicked.connect(Dialog.set_applySlot)
        self.out_comboBox.currentIndexChanged['int'].connect(Dialog.out_fmtSlot)
        self.reg_pushButton.clicked.connect(Dialog.reg_buttonSlot)
        self.adv_pushButton_add.clicked.connect(Dialog.adv_buttonAddSlot)
        self.adv_pushButton_help.clicked.connect(Dialog.adv_buttonHelpSlot)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "高级"))
        self.label_login.setText(_translate("Dialog", "登录"))
        self.login_label_id.setText(_translate("Dialog", "账号名"))
        self.login_label_key.setText(_translate("Dialog", "账户密码"))
        self.login_label_secret.setText(_translate("Dialog", "账户密钥"))
        self.label_reg.setText(_translate("Dialog", "识别"))
        self.reg_label_lay.setText(_translate("Dialog", "识别间隔:"))
        self.reg_timeEdit.setDisplayFormat(_translate("Dialog", "s秒"))
        self.reg_label_num.setText(_translate("Dialog", "识别数量:"))
        self.reg_comboBox.setItemText(0, _translate("Dialog", "所有"))
        self.reg_comboBox.setItemText(1, _translate("Dialog", "1"))
        self.reg_comboBox.setItemText(2, _translate("Dialog", "2"))
        self.reg_comboBox.setItemText(3, _translate("Dialog", "3"))
        self.reg_comboBox.setItemText(4, _translate("Dialog", "-1"))
        self.reg_comboBox.setItemText(5, _translate("Dialog", "-2"))
        self.reg_comboBox.setItemText(6, _translate("Dialog", "-3"))
        self.reg_pushButton.setText(_translate("Dialog", "帮助"))
        self.reg_label_debug.setText(_translate("Dialog", "识别模式:"))
        self.comboBox.setItemText(0, _translate("Dialog", "精准识别"))
        self.comboBox.setItemText(1, _translate("Dialog", "通用识别"))
        self.comboBox.setItemText(2, _translate("Dialog", "手写识别"))
        self.label_out.setText(_translate("Dialog", "导出"))
        self.out_label_fmt.setText(_translate("Dialog", "导出格式:"))
        self.out_label_dir.setText(_translate("Dialog", "导出目录:"))
        self.out_comboBox.setItemText(0, _translate("Dialog", "文本 txt"))
        self.out_comboBox.setItemText(1, _translate("Dialog", "Excel xlsx"))
        self.out_label_title.setText(_translate("Dialog", "标题设置:"))
        self.label_advanced.setText(_translate("Dialog", "高级"))
        self.adv_pushButton_help.setText(_translate("Dialog", "帮助"))
        self.adv_label_clean.setText(_translate("Dialog", "字段清洗:"))
        self.adv_pushButton_add.setText(_translate("Dialog", "添加"))
        self.adv_label_region.setText(_translate("Dialog", "识别区域:"))
        self.set_pushButton_reset.setText(_translate("Dialog", "重置"))
        self.set_pushButton_apply.setText(_translate("Dialog", "应用"))
